{
 "title": "DevOps Test",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",cpu=\"0\",mode=\"user\"}[1m]) ",
     "legendFormat": "CPU User"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node_exporter\",cpu=\"0\",mode=\"system\"}[1m])",
     "legendFormat": "CPU System"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_MemFree_bytes{job=\"node_exporter\"}[1m])",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "Diskspace for /",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(irate(node_filesystem_avail_bytes{job=\"node_exporter\",device=\"/dev/sda\",fstype=\"ext4\",mountpoint=\"/\"}[1m])/1/1)\n\n",
     "legendFormat": "Filesystem Root"
    }
   ]
  }
 ]
}